#!/bin/bash

base_folder=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)

case "$1" in
  "start")
    set -e
    echo "Building frontend..."
    cd "${base_folder}/resources/frontend"
    npm run build
    echo "Deleting redundant frontend files..."
    rm -f "${base_folder}/resources/frontend/build/asset-manifest.json"
    echo "Starting backend..."
    cd "${base_folder}"
    if [[ $# -gt 2 ]]; then
      cargo run --features "$(IFS=,; echo "${*:3}")"
    else
      cargo run
    fi
    ;;
  "build")
    set -e
    echo "Building frontend..."
    cd "${base_folder}/resources/frontend"
    npm run build
    echo "Deleting redundant frontend files..."
    rm -f "${base_folder}/resources/frontend/build/asset-manifest.json"
    echo "Building backend..."
    cd "${base_folder}"
    if [[ $# -gt 2 ]]; then
      cargo build --release --features "$(IFS=,; echo "${*:3}")"
    else
      cargo build --release
    fi
    echo "Preparing build directories..."
    mkdir -p "${base_folder}/build"
    echo "Removing old build files..."
    rm -f "${base_folder}/build/repox"
    echo "Copying final build to the build folder..."
    cp "${base_folder}/target/release/repox" "${base_folder}/build/repox"
    chmod +x "${base_folder}/build/repox"
    ;;
  *)
    echo "Available commands:"
    echo " * start [features...]"
    echo " * build [features...]"
    ;;
esac
