#!/bin/bash

base_folder=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)

case "$1" in
  "frontend")
    case "$2" in
      "start")
        set -e
        echo "Starting frontend..."
        cd "${base_folder}/resources/frontend"
        npm start
        ;;
      *)
        echo "Available commands:"
        echo " * start"
        ;;
    esac
    ;;
  "backend")
    case "$2" in
      "start")
        set -e
        echo "Starting backend..."
        cd "${base_folder}"
        cargo run --no-default-features
        ;;
      *)
        echo "Available commands:"
        echo " * start"
        ;;
    esac
    ;;
  "build")
    set -e
    echo "Building frontend..."
    cd "${base_folder}/resources/frontend"
    npm run build
    echo "Deleting redundant frontend files..."
    rm -f "${base_folder}/resources/frontend/build/asset-manifest.json"
    echo "Building backend..."
    cd "${base_folder}"
    cargo build --release
    echo "Preparing build directories..."
    mkdir -p "${base_folder}/build"
    echo "Removing old build files..."
    rm -f "${base_folder}/build/repox"
    echo "Copying final build to the build folder..."
    cp "${base_folder}/target/release/repox" "${base_folder}/build/repox"
    chmod +x "${base_folder}/build/repox"
    ;;
  *)
    echo "Available commands:"
    echo " * frontend <[start]>"
    echo " * backend <[start]>"
    echo " * build"
    ;;
esac
